version: '3.8'

services:
  # Databases
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: dealmate
      POSTGRES_USER: dealmate
      POSTGRES_PASSWORD: dealmate123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dealmate"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Gateway
  api-gateway:
    image: ghcr.io/Skylto-inc/dealmate-gateway:latest
    ports:
      - "80:80"
    depends_on:
      - user-service
      - product-service
      - deal-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Rust Microservices
  user-service:
    image: ghcr.io/Skylto-inc/dealmate-auth-api:latest
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://dealmate:dealmate123@postgres:5432/dealmate
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  product-service:
    image: ghcr.io/Skylto-inc/dealmate-catalog-service:latest
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://dealmate:dealmate123@postgres:5432/dealmate
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  deal-service:
    image: ghcr.io/Skylto-inc/dealmate-ai-engine:latest
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://dealmate:dealmate123@postgres:5432/dealmate
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  marketplace-service:
    image: ghcr.io/Skylto-inc/dealmate-marketplace:latest
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: postgresql://dealmate:dealmate123@postgres:5432/dealmate
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lootpacks-service:
    image: ghcr.io/Skylto-inc/dealmate-lootpacks:latest
    ports:
      - "8003:8003"
    environment:
      DATABASE_URL: postgresql://dealmate:dealmate123@postgres:5432/dealmate
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  comparison-service:
    image: ghcr.io/Skylto-inc/dealmate-comparison-engine:latest
    ports:
      - "8004:8004"
    environment:
      DATABASE_URL: postgresql://dealmate:dealmate123@postgres:5432/dealmate
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Node.js Services
  notification-service:
    image: ghcr.io/Skylto-inc/dealmate-alerts:latest
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgresql://dealmate:dealmate123@postgres:5432/dealmate
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Python AI Services
  dealbot-service:
    image: ghcr.io/Skylto-inc/dealmate-dealbot:latest
    ports:
      - "3009:3009"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3009/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  product-detection-service:
    image: ghcr.io/Skylto-inc/dealmate-product-detection:latest
    ports:
      - "3010:3010"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3010/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  fraud-detection-service:
    image: ghcr.io/Skylto-inc/dealmate-fraud-detection:latest
    ports:
      - "3011:3011"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3011/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  recommendation-service:
    image: ghcr.io/Skylto-inc/dealmate-recommendations:latest
    ports:
      - "3012:3012"
    environment:
      DATABASE_URL: postgresql://dealmate:dealmate123@postgres:5432/dealmate
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3012/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  scraping-service:
    image: ghcr.io/Skylto-inc/dealmate-scraping-engine:latest
    ports:
      - "3013:3013"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3013/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  analytics-service:
    image: ghcr.io/Skylto-inc/dealmate-insights:latest
    ports:
      - "3014:3014"
    environment:
      DATABASE_URL: postgresql://dealmate:dealmate123@postgres:5432/dealmate
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3014/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend-service:
    image: ghcr.io/Skylto-inc/dealmate-web-ui:latest
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:80
    depends_on:
      - api-gateway
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Browser Extension (for development/testing)
  browser-extension-service:
    image: ghcr.io/Skylto-inc/dealmate-extension:latest
    ports:
      - "3003:3003"

volumes:
  postgres_data:

networks:
  default:
    name: dealmate-network
