version: '3.8'

services:
  # Databases
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: dealmate
      POSTGRES_USER: dealmate
      POSTGRES_PASSWORD: dealmate123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  # API Gateway
  api-gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
      - product-service

  # Microservices (Docker images)
  user-service:
    image: ghcr.io/skylto-inc/dealmate-auth-api:latest
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://dealmate:dealmate123@postgres:5432/dealmate
    depends_on:
      - postgres

  product-service:
    image: ghcr.io/skylto-inc/dealmate-catalog-service:latest
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  deal-service:
    image: ghcr.io/skylto-inc/dealmate-ai-engine:latest
    ports:
      - "8001:8001"
    depends_on:
      - postgres

  frontend-service:
    image: ghcr.io/skylto-inc/dealmate-web-ui:latest
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:80

volumes:
  postgres_data:
